name: Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']
        appraisal: ['rails-7.2', 'rails-8.0', 'rails-8.1']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Run tests
      env:
        AWS_S3_URI: ${{ secrets.AWS_S3_URI }}
      run: bundle exec appraisal ${{ matrix.appraisal }} rake spec
